version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: incidents-backend
    ports:
      - "3000:3000"
    environment:
      - GIN_MODE=debug
    volumes:
      - ./backend:/app
      - go-mod:/go/pkg/mod
      - go-build:/root/.cache/go-build
      - uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: incidents-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  go-mod:
  go-build:
  uploads:
